// Copyright Finbuckle LLC, Andrew White, and Contributors.
// Refer to the solution LICENSE file for more information.

namespace Finbuckle.MultiTenant.Abstractions;

/// <summary>
/// An exception generated by Finbuckle.MultiTenant.
/// </summary>
public class MultiTenantException : Exception
{
    /// <summary>
    /// Initializes a new instance of MultiTenantException with a specified error message.
    /// </summary>
    /// <param name="message">The message that describes the error.</param>
    public MultiTenantException(string? message) : base(message)
    {
    }

    /// <summary>
    /// Initializes a new instance of MultiTenantException with a specified error message and a reference to the inner exception that is the cause of this exception.
    /// </summary>
    /// <param name="message">The error message that explains the reason for the exception.</param>
    /// <param name="innerException">The exception that is the cause of the current exception.</param>
    public MultiTenantException(string? message, Exception? innerException) : base(message, innerException)
    {
    }
}