// Copyright Finbuckle LLC, Andrew White, and Contributors.
// Refer to the solution LICENSE file for more inforation.

using System;

namespace Finbuckle.MultiTenant;

/// <summary>
/// A derived Exception class for any exception generated by Finbuckle.MultiTenant.
/// </summary>
public class MultiTenantException : Exception
{
    public MultiTenantException(string? message) : base(message)
    {
    }

    public MultiTenantException(string? message, Exception? innerException) : base(message, innerException)
    {
    }
}