name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    strategy:
      matrix:
        dotnet: ['10.0']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6.2.0
      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: 10
      - name: build
        run: dotnet build -p:ContinuousIntegrationBuild=true
      - name: test Finbuckle.MultiTenant
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }} -p:CollectCoverage=true
        working-directory: ./test/Finbuckle.MultiTenant.Test
      - name: test Finbuckle.MultiTenant.AspNetCore
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }} -p:CollectCoverage=true
        working-directory: ./test/Finbuckle.MultiTenant.AspNetCore.Test
      - name: test Finbuckle.MultiTenant.EntityFrameworkCore
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }} -p:CollectCoverage=true
        working-directory: ./test/Finbuckle.MultiTenant.EntityFrameworkCore.Test
      - name: test Finbuckle.MultiTenant.Identity.EntityFrameworkCore
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }} -p:CollectCoverage=true
        working-directory: ./test/Finbuckle.MultiTenant.Identity.EntityFrameworkCore.Test
      - name: upload coverage results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-${{ runner.os }}
          path: test/**/TestResults/Coverage/coverage.cobertura.xml
          if-no-files-found: error
          retention-days: 14
