name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6.2.0
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10
      - name: build
        run: dotnet build -p:ContinuousIntegrationBuild=true
      - name: test Finbuckle.MultiTenant
        run: dotnet test --no-build -v q
        working-directory: ./test/Finbuckle.MultiTenant.Test
      - name: test Finbuckle.MultiTenant.AspNetCore
        run: dotnet test --no-build -v q
        working-directory: ./test/Finbuckle.MultiTenant.AspNetCore.Test
      - name: test Finbuckle.MultiTenant.EntityFrameworkCore
        run: dotnet test --no-build -v q
        working-directory: ./test/Finbuckle.MultiTenant.EntityFrameworkCore.Test
      - name: test Finbuckle.MultiTenant.Identity.EntityFrameworkCore
        run: dotnet test --no-build -v q
        working-directory: ./test/Finbuckle.MultiTenant.Identity.EntityFrameworkCore.Test
        
