name: Linux (.NET 6.0)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  os-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        env:
          DOTNET_INSTALL_DIR: /usr/share/dotnet
      - name: test Finbuckle.MultiTenanant
        run: dotnet test -f net6.0
        working-directory: ./test/Finbuckle.MultiTenant.Test
      - name: test Finbuckle.MultiTenanant.AspNetCore
        run: dotnet test -f net6.0
        working-directory: ./test/Finbuckle.MultiTenant.AspNetCore.Test
      - name: test Finbuckle.MultiTenanant.EntityFrameworkCore
        run: dotnet test -f net6.0
        working-directory: ./test/Finbuckle.MultiTenant.EntityFrameworkCore.Test
        
