name: MacOS (.NET Core 3.1)

on:
  push:
    branches: [main]
  pull_request_target:

jobs:
  os-tests:
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
      - name: test Finbuckle.MultiTenanant
        run: dotnet test -f netcoreapp3.1
        working-directory: ./test/Finbuckle.MultiTenant.Test
      - name: test Finbuckle.MultiTenanant.AspNetCore
        run: dotnet test -f netcoreapp3.1
        working-directory: ./test/Finbuckle.MultiTenant.AspNetCore.Test
      - name: test Finbuckle.MultiTenanant.EntityFrameworkCore
        run: dotnet test -f netcoreapp3.1
        working-directory: ./test/Finbuckle.MultiTenant.EntityFrameworkCore.Test
