name: Pull Request Checks

on:
  pull_request:
    types: [open, reopen, synchronize]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        test-project:
          - Finbuckle.MultiTenant.Test/Finbuckle.MultiTenant.Test.csproj
          - Finbuckle.MultiTenant.AspNetCore.Test/Finbuckle.MultiTenant.AspNetCore.Test.csproj
          - Finbuckle.MultiTenant.EntityFrameworkCore.Test/Finbuckle.MultiTenant.EntityFrameworkCore.Test.csproj
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: setup dotnet 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
      - name: test
        run: dotnet test
        working-directory: ${{ matrix.test-project }}
