name: Pull Request - Run Tests

on:
  pull_request:
    types: [open, reopen, synchronize]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: setup dotnet 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
      - name: test
        run: dotnet test
